NOT_FOUND = "NOT FOUND"
ALREADY_EXISTS = "ALREADY EXISTS"
INVALID_PROTOCOL = "INVALID PROTOCOL"
CLIENT_DENIED = "ACCESS DENIED"
NOT_ENOUGH_FUNDS = "NOT ENOUGH MONEY"

class CustomError():
    pass