NOT_FOUND = "NOT FOUND"
ALREADY_EXISTS = "ALREADY EXISTS"
INVALID_PROTOCOL = "INVALID PROTOCOL"
CLIENT_DENIED = "ACCESS DENIED"
NOT_ENOUGH_FUNDS = "NOT ENOUGH FUNDS"
WRONG_DATA_TYPE = "WRONG DATA TYPE"

class CustomError():
    pass
